language: python

python:
    - 2.7
    - 3.6

env:
    global:
        - CMD='./runtests.py'

before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b -p $HOME/miniconda
    - export PATH=/home/travis/miniconda/bin:$PATH
    - conda update --yes conda

install:
    - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION
    - source activate test
    - pip install coveralls
    - pip install -U pip
    - python setup.py install

script: $CMD

after_success: coveralls
