language: python

sudo: required
dist: trusty

python:
    - 2.7
    - 3.6

before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b -p $HOME/miniconda
    - export PATH=/home/travis/miniconda/bin:$PATH
    - conda update --yes conda

install:
    - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION
    - source activate test
    - pip install -U pip
    - pip install coveralls pyflakes
    - pip install matplotlib==2.2.4
    - pyflakes dynesty/*.py
    - python setup.py install

script: python runtests.py

after_success: coveralls
