name: Dynesty

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
    

jobs:
  tester:
    name: Test the code
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.8]

    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Python setup
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'
      - name: Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
          pip install pylint
          pip install pytest-cov
          pip install coveralls
          pip install .
      - name: pylint
        run: pylint --fail-under=8 --extension-pkg-whitelist=scipy.special  py/dynesty/*py
      - name: RandomCheck
        # check that np.random is not used directly
        run: grep -e 'np\.random\.' py/*/*y  | ( ! grep -v plotting.py )
      - name: TestWithCov
        # Run coverage only for 3.6
        if: ${{ matrix.python-version == '3.6'}}
        run: pytest --durations=0 --cov=dynesty
      - name: Test
        if: ${{ matrix.python-version != '3.6'}}
        run: pytest --durations=0
      - name: Coveralls
        if: ${{ success() && ( matrix.python-version == '3.6') }}
        run: coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
